# Training Sources (40)
sources:
  - name: CNN
    url: https://www.cnn.com
    language: English
    group: News & Blogs/English
    rss: https://rss.cnn.com/rss/edition.rss

  - name: BBC
    url: https://www.bbc.com
    language: English
    group: News & Blogs/English
    rss: https://feeds.bbci.co.uk/news/rss.xml

  - name: New York Times
    url: https://www.nytimes.com
    language: English
    group: News & Blogs/English
    rss: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml

  - name: The Guardian
    url: https://www.theguardian.com
    language: English
    group: News & Blogs/English
    rss: https://www.theguardian.com/world/rss

  - name: Reuters
    url: https://www.reuters.com
    language: English
    group: News & Blogs/English
    rss: https://www.reuters.com/world/rss

  - name: Washington Post
    url: https://www.washingtonpost.com
    language: English
    group: News & Blogs/English
    rss: https://feeds.washingtonpost.com/rss/world

  - name: Forbes
    url: https://www.forbes.com
    language: English
    group: News & Blogs/English
    rss: https://www.forbes.com/business/feed/

  - name: TechCrunch
    url: https://techcrunch.com
    language: English
    group: News & Blogs/English
    rss: https://techcrunch.com/feed/

  - name: The Next Web
    url: https://thenextweb.com
    language: English
    group: News & Blogs/English
    rss: https://thenextweb.com/feed

  - name: Medium
    url: https://medium.com
    language: English
    group: News & Blogs/English
    rss: https://medium.com/feed/topic/technology

  - name: Dev.to
    url: https://dev.to
    language: English
    group: News & Blogs/English
    rss: https://dev.to/feed

  - name: Mashable
    url: https://mashable.com
    language: English
    group: News & Blogs/English
    rss: https://mashable.com/feeds/rss/

  - name: Wall Street Journal
    url: https://www.wsj.com
    language: English
    group: News & Blogs/English
    rss: https://feeds.a.dj.com/rss/RSSWorldNews.xml

  - name: WIRED
    url: https://www.wired.com
    language: English
    group: News & Blogs/English
    rss: https://www.wired.com/feed/rss

  - name: NPR
    url: https://www.npr.org
    language: English
    group: News & Blogs/English
    rss: https://feeds.npr.org/1001/rss.xml  # Top stories

  - name: Vox
    url: https://www.vox.com
    language: English
    group: News & Blogs/English
    rss: https://www.vox.com/rss/index.xml

  - name: Bloomberg
    url: https://www.bloomberg.com
    language: English
    group: News & Blogs/English
    # No broad public RSS; leave empty to let autodiscovery skip if none.

  - name: Seeking Alpha
    url: https://www.seekingalpha.com
    language: English
    group: News & Blogs/English
    rss: https://seekingalpha.com/market-news.xml

  - name: Engadget
    url: https://www.engadget.com
    language: English
    group: News & Blogs/English
    rss: https://www.engadget.com/rss.xml

  - name: The Verge
    url: https://www.theverge.com
    language: English
    group: News & Blogs/English
    rss: https://www.theverge.com/rss/index.xml

  - name: Financial Times
    url: https://www.ft.com
    language: English
    group: News & Blogs/English
    rss: https://www.ft.com/?format=rss

  - name: Ars Technica
    url: https://arstechnica.com
    language: English
    group: News & Blogs/English
    rss: https://feeds.arstechnica.com/arstechnica/index

  - name: CNET
    url: https://www.cnet.com
    language: English
    group: News & Blogs/English
    rss: https://www.cnet.com/rss/all/

  - name: Slashdot
    url: https://www.slashdot.org
    language: English
    group: News & Blogs/English
    rss: https://rss.slashdot.org/Slashdot/slashdotMain

  - name: HuffPost
    url: https://www.huffpost.com
    language: English
    group: News & Blogs/English
    rss: https://www.huffpost.com/section/front-page/feed?x=1

  - name: Al Jazeera (AR)
    url: https://www.aljazeera.net
    language: Arabic
    group: News & Blogs/Arabic
    rss: https://www.aljazeera.net/xml/rss/all.xml

  - name: Sky News Arabia
    url: https://www.skynewsarabia.com
    language: Arabic
    group: News & Blogs/Arabic
    # Their feeds are per-section under /web/rss-feed; keep autodiscovery or add a specific section feed here.

  - name: Al Arabiya
    url: https://www.alarabiya.net
    language: Arabic
    group: News & Blogs/Arabic
    rss: https://www.alarabiya.net/tools/mrss

  - name: Akhbaar 24
    url: https://www.akhbaar24.com
    language: Arabic
    group: News & Blogs/Arabic
    rss: https://akhbaar24.argaam.com/rss

  - name: Middle East Online
    url: https://middle-east-online.com
    language: Arabic
    group: News & Blogs/Arabic
    rss: https://middle-east-online.com/rss.xml

  - name: The National (EN+AR)
    url: https://www.thenationalnews.com
    language: Arabic
    group: News & Blogs/Arabic
    rss: https://www.thenationalnews.com/rss

  - name: CNN Arabic
    url: https://arabic.cnn.com
    language: Arabic
    group: News & Blogs/Arabic
    rss: https://arabic.cnn.com/rss

  - name: BBC Arabic
    url: https://www.bbc.com/arabic
    language: Arabic
    group: News & Blogs/Arabic
    rss: https://feeds.bbci.co.uk/arabic/rss.xml

  - name: Masaar (EN+AR)
    url: https://www.masaar.com
    language: Arabic
    group: News & Blogs/Arabic
    # Feed not reliably published; leave empty and rely on autodiscovery.

  - name: 9elp (Multilingual)
    url: https://9elp.com
    language: Arabic
    group: News & Blogs/Arabic
    # Feed unclear; leave empty for autodiscovery.

  - name: RT
    url: https://www.rt.com
    language: Russian
    group: News & Blogs/Russian
    rss: https://www.rt.com/rss/news/

  - name: TASS (EN+RU)
    url: https://tass.com
    language: Russian
    group: News & Blogs/Russian
    rss: https://tass.com/rss/v2.xml

  - name: RBC
    url: https://www.rbc.ru
    language: Russian
    group: News & Blogs/Russian
    rss: https://rssexport.rbc.ru/rbcnews/news/20/full.rss

  - name: Meduza (EN)
    url: https://meduza.io/en
    language: Russian
    group: News & Blogs/Russian
    rss: https://meduza.io/en/rss

  - name: Echo Moscow
    url: https://www.echo.msk.ru
    language: Russian
    group: News & Blogs/Russian
    # Site is discontinued; no working public feed. Leave empty so scraper skips.
